### ISSUE TITLE
Problem with using imagemin on linux with gulp@3.8.8

### ISSUE THREAD

**Issue by derberg** [bevry/safeps#6]
Reported here first: https://github.com/sindresorhus/gulp-imagemin/issues/81

This is what I have in my project:

```
"gulp-imagemin": "^2.0.0"
```

On Mac all works fine but when I run my gulp tasks on: Linux Debian 3.14.12-1 I get the following error:

```
    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:904:11)
        at Object.afterWrite (net.js:720:19)

      at ChildProcess.<anonymous> (/node_modules/safeps/out/lib/safeps.js:165:23)
      at ChildProcess.emit (events.js:98:17)
      at maybeClose (child_process.js:755:16)
      at Process.ChildProcess._handle.onexit (child_process.js:822:5)
```

**Comment by callumacrae** [comment]
@smashrobot is also having this problem, and loading [epipebomb] didn't fix it.

Any ideas?

[epipebomb]: https://www.npmjs.com/package/epipebomb

**Comment by nick-brown** [comment]
Having the same issue on a basic Centos 6.5, 6.6, and 7.1 AWS machine image.

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: write EPIPE
        at errnoException (net.js:905:11)
        at Object.afterWrite (net.js:721:19)

**Comment by bencorlett** [comment]
Same issue here, no idea what's causing it.

**Comment by yingnansong** [comment]
Same here. 

In a CentOS image on AWS EC2.

**Comment by mcblum** [comment]
Same here, Centos running on our own server.

**Comment by lya0** [comment]
npm install jpegtran-bin -S
do this;

**Comment by balupton** [comment]
if anyone can reproduce, get a time with me on https://balupton.com/meet

**Comment by balupton** [comment]
Closing as it's 8 years stale
